# Kimi API Configuration
model:
  api_key: "YOUR_API_KEY"  # Replace with your API key here
  base_url: "YOUR_Base_Url"
  model_name: "YOUR_Model_Name"
  temperature: 0.6
  top_p: 0.95

# Runtime Configuration
runtime:
  max_concurrent: 100      # Maximum number of concurrent requests
  retry_times: 3         # Number of retry attempts on failure
  retry_delay: 1         # Retry interval in seconds
  save_interval: 10      # Save checkpoint every N processed items
  log_level: "INFO"     # Logging level: DEBUG, INFO, WARNING, ERROR

# Input/Output Configuration
io:
  input_file: "YOUR_Input_File_Path"    # Input CSV file path
  output_file: "YOUR_Output_File_Path"            # Output CSV file path
  checkpoint_dir: "YOUR_Checkpoint_Dir"        # Checkpoint directory